# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\":\n\x0b\x43hatMessage\x12\x10\n\x08\x66romUser\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x0c\n\x04time\x18\x03 \x01(\t\" \n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x07\n\x05\x45mpty\" \n\x08UserList\x12\x14\n\x05users\x18\x01 \x03(\x0b\x32\x05.User\"\x1b\n\x0cJoinResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t\"!\n\x11ReceiveMsgRequest\x12\x0c\n\x04user\x18\x01 \x01(\t2\x96\x01\n\x0b\x43hatService\x12\x1e\n\x04join\x12\x05.User\x1a\r.JoinResponse0\x01\x12\x1f\n\x07sendMsg\x12\x0c.ChatMessage\x1a\x06.Empty\x12$\n\nreceiveMsg\x12\x06.Empty\x1a\x0c.ChatMessage0\x01\x12 \n\x0bgetAllUsers\x12\x06.Empty\x1a\t.UserListb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHATMESSAGE._serialized_start=14
  _CHATMESSAGE._serialized_end=72
  _USER._serialized_start=74
  _USER._serialized_end=106
  _EMPTY._serialized_start=108
  _EMPTY._serialized_end=115
  _USERLIST._serialized_start=117
  _USERLIST._serialized_end=149
  _JOINRESPONSE._serialized_start=151
  _JOINRESPONSE._serialized_end=178
  _RECEIVEMSGREQUEST._serialized_start=180
  _RECEIVEMSGREQUEST._serialized_end=213
  _CHATSERVICE._serialized_start=216
  _CHATSERVICE._serialized_end=366
# @@protoc_insertion_point(module_scope)
